### ISSUE TITLE
Countries and Money gems should either be a runtime dependency or not required

### ISSUE THREAD

**Issue by Borzik** [facebook/facebook-ruby-business-sdk#101]
### Which SDK version are you using?
0.7.0.0
### What's the issue?
`countries` and `money` gems are required in file but not added as runtime dependencies, so `LoadError` is raised on `FacebookAds::ServerSide::UserData.new` calls.
### Steps/Sample code to reproduce the issue
Put this into a file and execute:
```ruby
require 'bundler/inline'
gemfile do
  source 'https://rubygems.org'
  gem 'facebookbusiness'
  # uncomment both lines to fix the code
  # gem 'countries'
  # gem 'money'
end
FacebookAds::ServerSide::UserData.new
puts 'success!'
```

#### Observed Results:

`LoadError` raised

#### Expected Results:

`success!` printed

**Comment by PlugIN73** [comment]
I have this problem too.

**Comment by jiehanzheng** [comment]
Yea I can confirm this too.  I will find someone to fix

**Comment by GarrettJMU** [comment]
Confirmed issue as well. Install gems and all is well.

**Comment by roots-ai** [comment]
getting `NameError: uninitialized constant FacebookAds::ServerSide`

**Comment by gaga5lala** [comment]
I've tested the sample code with `ruby 2.6.6p146` and both `0.7.0.0`, `0.7.0.2`. `success!` printed without error.

**Comment by Borzik** [comment]
Was fixed by https://github.com/facebook/facebook-ruby-business-sdk/commit/c20dfd7a6ebbe2dd3d195bc22e8e36941f826071
