### ISSUE TITLE
SDK faraday dependency

### ISSUE THREAD

**Issue by al13bash** [facebook/facebook-ruby-business-sdk#102]
### Which SDK version are you using?
0.3.3.3

### What's the issue?
SDK is not working properly and I cannot update SDK to the latest version, because on the project we are using faraday v1.0.1 and as I can see you restrict faraday to `s.add_dependency 'faraday', '~> 0.15'` starting from SDK version 0.3.3.4

### Steps/Sample code to reproduce the issue
My Gemfile contains the following
```
gem 'facebookbusiness'
gem 'faraday', '~> 1.0.1'
```
Gemfile.lock
```
facebookbusiness (0.3.3.3)
    faraday
    json
```

#### Observed Results:

  * What happened?  This could be a description, log output, etc.

That's what I see in the console when try to use `User`
```
Loading development environment (Rails 6.0.2.2)
2.7.0 :001 > FacebookAds::User.deserializer
Traceback (most recent call last):
        1: from (irb):1
NoMethodError (undefined method `achieves' for :games:Symbol)
```
That's why I started trying different gem versions and workarounds. I can confirm that everything works fine with downgraded faraday or updated gemspec (with updated faraday dependency). I would prefer to not downgrade faraday, so it would be nice if you can update gemspec so that we don't need to fork, but can use your up-to-date gem.

#### Expected Results:

  * What did you expect to happen?
I expect to use the latest SDK with faraday >= 1.0.1

Thanks!

**Comment by jairobluecaribu** [comment]
Hello,
I have the same problem with version facebookBusiness 0.7.0.1. So, I had to uninstall faraday v 1.0.1 and replace it for v 0.17.3 instead. that's worked for me.

**Comment by nitsujri** [comment]
We forked and bumped the Faraday version w/o touching anything else. It [works for us](https://github.com/jenfi-eng/facebook-ruby-business-sdk) and our use case, so YMMV.

**Comment by al13bash** [comment]
Hello @nitsujri,
Thanks for your comment! That's exactly what I've done for now. The main goal of this issue is to bring it up to the devs. 😄
