### ISSUE TITLE
Gem Version 0.8.0, `You are calling a deprecated version of the Ads API. Please update to the latest version: v9.0.`

### ISSUE THREAD

**Issue by dringbraze** [facebook/facebook-ruby-business-sdk#119]
### Which SDK version are you using?
0.8.0

### What's the issue?
Using version 0.8.0 we are seeing the following error response from the Facebook API
```
(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v9.0.:  (fbtrace_id: A9aMnq6KODwyOJSLY7jteNf)
```
### Steps/Sample code to reproduce the issue

Call the Facebook API using version 0.8.0

#### Observed Results:

  * What happened?  This could be a description, log output, etc.

Error response code 
```
(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v9.0.:  (fbtrace_id: A9aMnq6KODwyOJSLY7jteNf)
```

#### Expected Results:

  * What did you expect to happen?
For the API calls to succeed.

As per Facebook's API version support documentation, version 0.8.0 should be supported and *not* returning the above error.
https://developers.facebook.com/docs/graph-api/changelog/versions/

**Comment by mykoweb** [comment]
@dringbraze Did you do anything to get this working again? If so could you post your fix here?

**Comment by dringbraze** [comment]
Forced upgrade for the gem, not ideal, but it did resolve the issue.
