### ISSUE TITLE
Support Ruby 3.0.0

### ISSUE THREAD

**Issue by IanVaughan** [facebook/facebook-ruby-business-sdk#127]
### Which SDK version are you using?
`0.9.0.2`

### What's the issue?

Cannot bundle install the gem on ruby 3.0.0

### Steps/Sample code to reproduce the issue

`Gemfile` :
```
source 'https://rubygems.org'
ruby '3.0.0'
gem 'facebookbusiness'
```

```
> bundle install

Bundler found conflicting requirements for the Ruby version:
  In Gemfile:
    Ruby (~> 3.0.0.0)

    facebookbusiness (~> 0.9.0.2) was resolved to 0.9.0.2, which depends on
      Ruby (~> 2.0)
```

#### Expected Results:

It should install ok

**Comment by matthieua** [comment]
Could someone please look into this? We can't upgrade to Ruby 3 because of this.

**Comment by wilsonsilva** [comment]
Hey @IanVaughan! I was about to suggest the same :D

**Comment by matthieua** [comment]
Here's a potential solution https://github.com/facebook/facebook-ruby-business-sdk/pull/129 

Can someone at Facebook please look into this?

**Comment by IanVaughan** [comment]
Fixed via https://github.com/facebook/facebook-ruby-business-sdk/pull/129

**Comment by matthieua** [comment]
Thanks a lot @IanVaughan ! Just upgraded to Ruby 3.0!
