### ISSUE TITLE
Issue with gem version 0.10.0 creating unwanted custom events instead of using standard events

### ISSUE THREAD

**Issue by matthieua** [facebook/facebook-ruby-business-sdk#132]
Since upgrading to 10.0, the tracking has been wrong. We are tracking SubmitApplication which is a standard event but it created a custom event on the Facebook side called SubmitApplication and it's not being detected as a standard event anymore. Therefore we cannot optimize for this event anymore and we don't see results or attribution anymore.

We send SubmitApplication event using the Server Side API and it shows as "SubmitApplication" event on the Facebook side instead of "Submit Application" with space which would be considered as a standard event.
![Skærmbillede 2021-03-08 kl  17 59 46](https://user-images.githubusercontent.com/234575/110361616-2f003a00-8038-11eb-905f-a820aa2d3f80.png)

Do you mind looking into it? I'm downgrading to 0.9.0.3 and Ruby as well. @IanVaughan

**Comment by matthieua** [comment]
Have you had a chance to look into this @IanVaughan?

**Comment by IanVaughan** [comment]
I think you are tagging the wrong person, sorry I cannot help.

**Comment by matthieua** [comment]
any updates on this? This issue still persists and we can only use one word standard events because of this

**Comment by matthieua** [comment]
Sorry I mispelled. SubmitApplication, my bad
