### ISSUE TITLE
Event configuration (IOS 14 updates) missing

### ISSUE THREAD

**Issue by carsonbland** [facebook/facebook-ruby-business-sdk#135]
### Which SDK version are you using?
v10
### What's the issue?
Event configurations for aggregated event measurement do not have api documentation or code generation for updating via API/SDK.

#### Observed Results:
No api documentation or code generation to prioritize events across domains that have been verified.

Expecting API documentation for event configuration:
https://www.facebook.com/business/help/422408905612648

#### Expected Results:
API documentation or SDK code generation for updating event configuration.
It would also be helpful to be able to pull verification tags/keys from facebook in order to verify websites programmatically.

**Comment by Mth0158** [comment]
Arf, that's too bad...

The issue for me is to be able, once we have created a custom conversion, to associate this custom conversion to a domain web event. The API call does not seem to even exist yet?
I thought your issue was addressing this topic but I am not so sure anymore when I read your answer? 😅

**Comment by Mth0158** [comment]
@jingping2015 Do you know if "aggregated event measurement" functionalities will be implemented soon? It seems it is not implemented in Fb API either

**Comment by alanho** [comment]
closing this since this is not a Ruby SDK specific issue. you can post this question to https://developers.facebook.com/community which is more suitable for more general question like this.
