### ISSUE TITLE
Action Source "app" is valid value or not?

### ISSUE THREAD

**Issue by WaKeMaTTa** [facebook/facebook-ruby-business-sdk#157]
`FacebookAds::ServerSide::ActionSource` is an set of values:

```ruby
["email", "website", "app", "phone_call", "chat", "physical_store", "system_generated", "other"]
```
I can't find the value `"app"` in the [official documentation](https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/server-event#action-source).

My question is `"app"` is a valid value or not?

**Comment by alanho** [comment]
"app" is valid value. the documentation probably updated since this issue was opened. so i will mark this as resolved for now.
