### ISSUE TITLE
Can't pull campaigns from Ad Accounts

### ISSUE THREAD

**Issue by RecruboMark** [facebook/facebook-ruby-business-sdk#187]
### Which SDK version are you using?
facebookbusiness-0.15.0.0

### What's the issue?
I am unable to pull all campaigns from an Ad Account

### Steps/Sample code to reproduce the issue
1. Create a session object from an access_token
2. Pull account name from API
3. Pull campaign name from API
4. Try to pull the campaign from the ad account
<img width="935" alt="image" src="https://user-images.githubusercontent.com/52448924/202187082-b033c2c4-2770-45b8-a020-7d2305407293.png">

#### Observed Results:
`Tried accessing nonexisting field (campaigns) on node type (Page)`
I could not pull the campaigns that belong to an ad account from the API.

#### Expected Results:
I was expecting to be able to pull all Campaigns by first pulling the ad account and then trying to fetch all campaigns.
To display I do have the rights to pull both AdAccount information & Campaign information i've pulled them individually in the screenshot.

**Comment by stcheng** [comment]
the ID is not an ad account ID but a page ID
