### ISSUE TITLE
undefined method `configure' for FacebookAds:Module (NoMethodError)

### ISSUE THREAD

**Issue by jay754** [facebook/facebook-ruby-business-sdk#190]
### Which SDK version are you using?
0.7.0

### What's the issue?

undefined method `configure' for FacebookAds:Module (NoMethodError)

### Steps/Sample code to reproduce the issue

just run ruby 

#### Observed Results:

  * What happened?  This could be a description, log output, etc.

#### Expected Results:

  * What did you expect to happen?
to be working

**Comment by alanho** [comment]
can you update to the latest version and try again? 0.7.0 is a very old version, updating to the latest version might solve this issue.
