### ISSUE TITLE
Custom Properties Feature is not supported for Server-Side API in Ruby SDK

### ISSUE THREAD

**Issue by antoinecld** [facebook/facebook-ruby-business-sdk#191]
### Which SDK version are you using?
facebookbusiness (0.15.0.2)

### What's the issue?
We wand to add a custom property : `new_customer`
But Custom Properties Feature don't seem to work for Server-Side API in Ruby SDK.
However this feature is described at the end of the developer page 👇
<img width="821" alt="Capture d’écran 2023-02-04 à 15 32 32" src="https://user-images.githubusercontent.com/22981148/216773087-7d152a0f-363e-4528-8753-46ac1c94320c.png">
https://developers.facebook.com/docs/marketing-api/server-side-api/parameters/custom-data#custom-properties

#### Steps/Sample code to reproduce the issue
Try to add a custum properties

#### Observed Results:
```
ArgumentError: unknown keyword: :new_customer
from /Users/pro/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/facebookbusiness-0.15.0.2/lib/facebook_ads/ad_objects/server_side/event.rb:81:in `initialize'
```

#### Expected Results:
To be working

**Comment by alanho** [comment]
custom properties is currently supported, you can put custom properties in the custom data

```
custom_data = FacebookAds::ServerSide::CustomData.new(currency: 'usd', custom_properties: {new_customer: 1})

event = FacebookAds::ServerSide::Event.new(
        event_name: 'Purchase',
        event_time: Time.now.to_i,
        user_data: user_data,
        custom_data: custom_data,
        event_source_url: 'http://jaspers-market.com/product/123',
        action_source: 'website'
    )
```
