### ISSUE TITLE
Support for app_data field

### ISSUE THREAD

**Issue by corincerami** [facebook/facebook-ruby-business-sdk#192]
### Which SDK version are you using?

0.15.0.2

### What's the issue?

In order to not expose secrets like the Conversions API access token to our native apps, we're having the native apps communicate with the server and then sending events to the Conversions API from the server. However, this SDK doesn't support the `app_data` field on events. Is there some reason for specifically excluding this field here, or is it just that the use case hasn't come up before?

**Comment by stcheng** [comment]
Thanks for raising up this topic. We are working on this and the feature will be supported shortly within a minor release in v16. Stay tuned.

**Comment by corincerami** [comment]
Would it be helpful to submit a PR?

**Comment by corincerami** [comment]
@stcheng Hi, are there any estimates for when this feature might be released? Is it likely to be a few days, few weeks, few months? Thanks!

**Comment by stcheng** [comment]
@corincerami the current estimation is by the end of feb.

**Comment by stcheng** [comment]
This is addressed in the commit https://github.com/facebook/facebook-ruby-business-sdk/commit/18af4e11f3784fb9b5dd2c81177d4e955590a0d5
