### ISSUE TITLE
facebookbusiness README says that Ruby v2 is sufficient but the gemspec says otherwise

### ISSUE THREAD

**Issue by raymondweidner** [facebook/facebook-ruby-business-sdk#199]
### Which SDK version are you using?

- facebookbusiness v15.0.1
- ruby 2.7

### What's the issue?
We want to upgrade to v16 or v17. The README says "We developed this SDK using Ruby 2.0, and supports Ruby 2.0+..." However, the gemspec has the following line:

`s.required_ruby_version = '>= 3.0'`

Our organization is currently on Ruby v2.7, and we are planning to upgrade to Ruby 3x in the next few quarters. However, v15 of `facebookbusiness` is slated for end-of-life on 2023-08-15. Upgrading our version of Ruby in that timeframe is not feasible.

Is Ruby v3 really necessary for `facebookbusiness`? If not, it would be great if the gemspec could be updated accordingly. If so, it would be a good idea to update the README. 

### Steps/Sample code to reproduce the issue

N/A

#### Observed Results:

Attempting to upgrade facebookbusiness to v17 yielded the following output:

```
% gem update facebookbusiness
Updating installed gems
Updating facebookbusiness
Fetching facebookbusiness-17.0.1.gem
ERROR:  Error installing facebookbusiness:
	There are no versions of facebookbusiness (= 17.0.1) compatible with your Ruby & RubyGems
	facebookbusiness requires Ruby version >= 3.0. The current ruby version is 2.7xxx.
```

#### Expected Results:

That it would have succeeded.

**Comment by stcheng** [comment]
Thank you @raymondweidner we have recently updated our requirement to use Ruby 3.0+. We'll update the documentation to point this out.
