### ISSUE TITLE
Graph API V12.0 Deprecation 

### ISSUE THREAD

**Issue by elektramurphy** [facebook/facebook-ruby-business-sdk#208]
### Which SDK version are you using?
17.0.2

### What's the issue?
The [Graph API V12.0 is deprecating today ](https://developers.facebook.com/docs/graph-api/changelog). I want to confirm that that API is being maintained within this SDK. It's not completely clear with the documentation that the Graph API is part of the SDK.

**Comment by stcheng** [comment]
thanks for asking. SDK is a shim layer on top of Graph API and Marketing API. So SDK itself does not have any concepts of "deprecation".

Graph API v12.0 is deprecated meaning that developers are no longer able to call APIs with the version set to v12.0 for Graph APIs. In SDK, the default version is aligned with the latest Graph API version. If you stick to the latest version of the SDK, you will be calling the latest version of the API set unless you manually patch the SDK to call the specific version.
