### ISSUE TITLE
Get Amount spend from campaign

### ISSUE THREAD

**Issue by Michael3434** [facebook/facebook-ruby-business-sdk#35]
Hey, I cannot get from a campagin the amount spend.
I tryed many fields ( dayli_spend, spend, amount spend etc.. ) : 
undefined method `amount_spent' for #<FacebookAds::Campaign:0x007f8903ae49b0>
Any ideas ?

Thanks :)

**Comment by gregersen12** [comment]
I can confirm that this works :-)
