### ISSUE TITLE
Question about "facebook-ruby-ads-sdk custom audience" registration

### ISSUE THREAD

**Issue by sankak** [facebook/facebook-ruby-business-sdk#37]
Hi, I am trying to make a registration of a custom audience using "facebook-ruby-ads-sdk" (gem is below).
I am using the source below.
https://github.com/facebook/facebook-ruby-ads-sdk/blob/v0.2.11.0/lib/facebook_ads/ad_objects/helpers/custom_audience_helpers.rb

When I specify the schema "UID" and use the method "add_user", 
"is_raw" parameter is set to "true" in the library, and request to the Marketing API got sent.

The UID is hashed based on Digest::SHA256.hexdigest(data) in the gem.
When data is hashed, which "is_raw" parameter is correct, "true" or "false" ?

I appreciate for your support.

**Comment by yandod** [comment]
@sankak could you provide minimal code sample reproduce that issue?

**Comment by sankak** [comment]
here is sample source code.
```
@ad_acc = FacebookAds::AdAccount.get("act_XXXXXXXXXX",  {
    access_token: "YYYYYYYYYYY",
    app_secret: "ZZZZZZZZZZZZZZ"
})

@ca = @ad_acc.customaudiences.create({
  name: "name",
  subtype: "CUSTOM",
  description: "description",
})

# ids is examples for app scoped user id.
ids=[99999999990, 999999999991, 999999999992] 

# 00000000000000 is example for FB application id.
# ids is hashed in add_user method in the gem
@ca.add_user(ids, 'UID', {app_ids: [00000000000000]})

```
then, send marketing api with is_raw paramater true.

**Comment by yandod** [comment]
お待たせして申し訳ありません。
状況を確認いたしました。
すでに対策されているかもですが、上記のユースケースだけで言えば pre_hashedにtrueを指定すれば is_rawがtrueでデータもrawのリクエストを作れそうです。

      p @ca.prepare_params(ids, 'UID', {app_ids: ['936846693102846'], pre_hashed: true})
      {:payload=>{:schema=>"UID", :data=>["99999999990", "999999999991", "999999999992"], :is_raw=>true, :app_ids=>["936846693102846"]}}

そもそもハッシュ化した形で送信する仕様にすべきどうかで、gem自体の修正方針が変わってきますのでこちらは引き続き確認いたします。

**Comment by sankak** [comment]
ご連絡ありがとうございます。
pre_hashedにtrueを指定した所、正常にカスタムオーディエンスが登録できました。
