### ISSUE TITLE
JSON::GeneratorError:only generation of JSON objects or arrays allowed

### ISSUE THREAD

**Issue by yokuba** [facebook/facebook-ruby-business-sdk#41]
I have set up a sandbox account and cannot create an ad, even after successfully obtaining the creative, adset, etc.

Failures:

  1) FacebookAdsClient (development only tests) creates an ad
     Failure/Error:
       @ad_account.ads.create({
         adset_id: "120330000021336603",
         tracking_specs: "146149006094052",
         name: "Track this",
         creative: { creative_id: "120330000018226903" }
         })
     
     JSON::GeneratorError:
       only generation of JSON objects or arrays allowed
      /usr/local/rvm/gems/ruby-2.3.3/gems/json-1.8.6/lib/json/common.rb:223:in `generate'
      /usr/local/rvm/gems/ruby-2.3.3/gems/json-1.8.6/lib/json/common.rb:223:in `generate'
     /usr/local/rvm/gems/ruby-2.3.3/gems/facebookads-0.2.11.0/lib/facebook_ads/field_types/object.rb:29:in `serialize'
    /usr/local/rvm/gems/ruby-2.3.3/gems/facebookads-0.2.11.0/lib/facebook_ads/param_set.rb:51:in `block in to_params'
     /usr/local/rvm/gems/ruby-2.3.3/gems/facebookads-0.2.11.0/lib/facebook_ads/param_set.rb:39:in `each'
    /usr/local/rvm/gems/ruby-2.3.3/gems/facebookads-0.2.11.0/lib/facebook_ads/param_set.rb:39:in `map'
    /usr/local/rvm/gems/ruby-2.3.3/gems/facebookads-0.2.11.0/lib/facebook_ads/param_set.rb:39:in `to_params'
     /usr/local/rvm/gems/ruby-2.3.3/gems/facebookads-0.2.11.0/lib/facebook_ads/edge.rb:92:in `create'
    ./lib/facebook_ads_client.rb:74:in `create_ad'

**Comment by praveenangyan** [comment]
+1

**Comment by yokuba** [comment]
Used patch found here https://github.com/facebook/facebook-ruby-ads-sdk/pull/33

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
