### ISSUE TITLE
How to get 'X-FB-Ads-Insights-Throttle' header from response?

### ISSUE THREAD

**Issue by joaquincorrales** [facebook/facebook-ruby-business-sdk#48]
Trying to create a scheduled job to fetch insights from customer ad accounts but I need to constantly check the 'X-FB-Ads-Insights-Throttle' header in order to make sure Facebook doesn't limit me.

How can I check this header when calling the insights calls using the library?

**Comment by joephayes** [comment]
Check the `last_api_response` of the ad object you are using. You can access the headers from there. See https://github.com/facebook/facebook-ruby-business-sdk/issues/50#issuecomment-405943862 for an example.

**Comment by joaquincorrales** [comment]
Joe thanks a lot. I'm also trying to handle an ad account being limited or app being limited and catching it with a begin -> rescue but the last_api_response can't be found in the rescue. Maybe I should just make sure it never happens as opposed to trying to handle when it does

**Comment by joaquincorrales** [comment]
I'm already performing some sort of "ping" to the ad account before performing anything so I might be good but you can never be too safe. 

There's always the scenario that when you ping the adaccount everything is fine but halfway through processing they reach their limit you know

**Comment by joephayes** [comment]
Does this help at all?

```

begin
  ad_account = FacebookAds::AdAccount.get("act_#{ad_account_id}", 'name')

  puts "Ad Account Name: #{ad_account.name}"
rescue FacebookAds::APIError => e
  puts "fb_message: #{e.fb_message}"
  puts "type: #{e.type}"
  puts "code: #{e.code}"
  puts "error_subcode: #{e.error_subcode}"
  puts "is_transient: #{e.is_transient}"
  puts "error_user_title: #{e.error_user_title}"
  puts "error_user_msg: #{e.error_user_msg}"
  puts "fbtrace_id: #{e.fbtrace_id}"
end

```

**Comment by joephayes** [comment]
Ack - just realized - probably not since you need the header. My bad!

**Comment by joaquincorrales** [comment]
That helps tremendously thank you so much Joe! 

One last question. Do you know if there's an option to not allow users to edit campaigns made through the API in their ads managers? Or is that impossible.

**Comment by joephayes** [comment]
You are welcome! Unfortunately, I don't know if there is a way to block users from editing API created campaigns with Ads Manager. Sorry!
