### ISSUE TITLE
read after write not working for adimages?

### ISSUE THREAD

**Issue by joephayes** [facebook/facebook-ruby-business-sdk#50]
No matter what I put in `fields` I always get back image hash and url

I modified the example image_upload.rb file as follows:

```
images = ad_account.adimages.create({
  logo1: File.open(File.expand_path("../logo1.jpg", __FILE__)),
  logo2: File.open(File.expand_path("../logo2.png", __FILE__)),
  fields: ['name','hash']
})

```

and the object I get back contains `hash` and `url` attributes.

```
#<FacebookAds::AdImage {:hash=>"XXXXXXXXXX", :url=>"https://scontent.xx.fbcdn.net/v/t45.1600-4/XXXXXXXXXX"}>

```
Is read after write supported for ad images?

**Comment by joaquincorrales** [comment]
I don't think so. What are you trying to accomplish?

Also, do you know if there's anyway for us to catch error codes? The exception for a limited app or an invalid access token can only be caught as a string with a begin rescue.

**Comment by joaquincorrales** [comment]
The name of the image is assigned on upload. Use that name and the hashes that come back

**Comment by joephayes** [comment]
> Also, do you know if there's anyway for us to catch error codes? The exception for a limited app or an invalid access token can only be caught as a string with a begin rescue.

I don't.

**Comment by joephayes** [comment]
One thing I did find is that we can get to the last API response:

```
...
results = ad_account.adimages.create(files_to_upload)

last_response = ad_account.instance_variable_get(:@last_api_response)

puts last_response
```

returns something like this:

```
#<FacebookAds::APIResponse:0x00007fc21ec19e30 @status_code=200, @headers={"access-control-allow-origin"=>"*", "pragma"=>"no-cache", "cache-control"=>"private, no-cache, no-store, must-revalidate", "facebook-api-version"=>"v3.0", "expires"=>"Sat, 01 Jan 2000 00:00:00 GMT", "x-fb-rev"=>"4114154", "content-type"=>"application/json; charset=UTF-8", "x-fb-trace-id"=>"C75nfP1uUa2", "strict-transport-security"=>"max-age=15552000; preload", "vary"=>"Accept-Encoding", "x-fb-debug"=>"p1jZVk1qqErD5cO02AnAvHEIf6x0fL7R7TphrV2hzZvbivyXWzohS9CYOPRmp0Q5vTOTxe7VPPiTRvuCgy3G1g==", "date"=>"Wed, 18 Jul 2018 14:04:01 GMT", "connection"=>"close", "content-length"=>"425"}, @body="{\"images\":{\"elephant.png\":{\"hash\":\"XXXXX\",\"url\":\"https:\\/\\/scontent.xx.fbcdn.net\\/v\\/t45.1600-4\\/XXXXX\"},\"nodejs-logo.png\":{\"hash\":\"XXXXX\",\"url\":\"https:\\/\\/scontent.xx.fbcdn.net\\/v\\/t45.1600-4\\/XXXXX\"},\"MongoDB-Logo.png\":{\"hash\":\"XXXXXX\",\"url\":\"https:\\/\\/scontent.xx.fbcdn.net\\/v\\/t45.1600-4\\/XXXXXXXX\"}}}">

```

That would allow you to check for status codes, etc.

**Comment by joephayes** [comment]
Could someone from Facebook weigh in here though? Are there plans to support read after write when creating ad images? Or is it already supported and I did something wrong in my code?

**Comment by joephayes** [comment]
@alanho - Thanks for the response and that it what I'm doing. I did realize the name comes back in the response and so I'm using the `last_api_response` property of the ad account to get at them (see my comment above - https://github.com/facebook/facebook-ruby-business-sdk/issues/50#issuecomment-405943862)

If this is the case, then what is the use of the `fields` key when you create ad images? See the example image upload file - https://github.com/facebook/facebook-ruby-business-sdk/blob/master/examples/image_upload.rb
