### ISSUE TITLE
Fetching preview for ad creative returns broken URL

### ISSUE THREAD

**Issue by iamricks** [facebook/facebook-ruby-business-sdk#54]
I am fetching a preview like so:

`FacebookAds::AdCreative.get(creativeId, session).previews(ad_format: adFormat)`

Every single preview i fetch the URL comes like this:

"https://www.facebook.com/ads/api/preview_iframe.php...........&amp;t=AQK0********XnH5"

Notice how the "t" param has a ";" instead of a "&"

This is causing the links to return "The parameter t is required"

**Comment by rs-joaki** [comment]
Any updates on this?

**Comment by jnmcdonald** [comment]
I am using the python sdk but I'm hitting the same error with the following code: 

fields = [
]
params = {
  'ad_format': 'DESKTOP_FEED_STANDARD',
}
r = AdCreative(id).get_previews(
  fields=fields,
  params=params,
)

**Comment by iamricks** [comment]
@jnmcdonald Yeah... its never been fixed. I think i just replaced the `;` with a `&` as a tempt fix and it just stayed like that after it not being fixed for over a year, i no longer use that endpoint because the feature was removed. Facebook's API can be a pain.

**Comment by jnmcdonald** [comment]
@iamricks yeah, I did the same thing in my code, it's just frustrating that hasn't been addressed. I'll reach out to a solutions engineer.

**Comment by vpatil1999** [comment]
- **_Hello guys ,  the preview link meta returns ,  uses `;` to separate query params, which isn’t supported everywhere. Globally, `&` is standard. I tested replacing `;` with `&`, we can proceed with this approach , may it helps._**

```js
const processIframeData = (data) => data.data.map(({ body }) => body.match(/src="([^"]+)"/)[1].replace(/;/g, '&'));

const input = {
   "data": [
       {
           "body": "<iframe src=\"https://business.facebook.com/ads/api/preview_iframe.php?d=AQJ4J3tDRVmIuyoO4FiDPiklry8Q0lymZAHAVyiUbjPLBl20DH9oINJKbrf4w4kiipdQUHGXNZhCyDr3ptLpLiCTKSm959NHxCzcJh-76VY2Zwf3WrMv_KrI68Qd9oS9AcuIUea4fPZQdoNMeB5OIbRD7HP-vswxkU7kuCgFp6vJfQQb_dDOnhdgIwjRmXcxdY4r6Rrm79f0pNTf8WjIxKi8M4GM0IS8VDflUFLBqjyeFZEOUsPSeLwrtGxjlAfcHeKmRk8cNZHL7reiCYRmuQBig-bYXu7mZCryFSKGfyLy0XI7Ih7R4WD7GNzwJU35lESa4m3CroLZE7WnBEM-If-YTDW1Dog6kPepp1NPB-TD3lrIUthOFRTPZyw53CoKP7W22YaAsGWb1w9kB8Vd8aMfOXROqRlaWGRUyYa7Owr7fAR5YCtxf2ZkASLLyV7UoBg&amp;t=AQI5DE58MrcIMYML4UE\" width=\"540\" height=\"690\" scrolling=\"yes\" style=\"border: none;\"></iframe>"
       }
   ]
};

console.log(processIframeData(input));

```
