### ISSUE TITLE
Invalid parameter: Ambiguous Promoted Object Fields

### ISSUE THREAD

**Issue by OrrYakobiStudent** [facebook/facebook-ruby-business-sdk#6]
I am getting this error, "Invalid parameter: Ambiguous Promoted Object Fields", when I try to create my ad. I have followed the code in the example you have provided. Here is my code for reference:

      #Create ad campaign
      campaign = ad_account.campaigns.create({
        name: params[:campaign_name],
        objective: 'LINK_CLICKS'
      })

      #Create adsets
      ad_set = ad_account.adsets.create({
        name: 'Test ad set' ,
        campaign_id: campaign.id,
        bid_amount: 1000,
        billing_event: 'LINK_CLICKS',
        daily_budget: 15000, #params[:daily_budget],
        targeting: {
          age_max: params[:age_max],
          age_min: params[:age_min],
          geo_locations: {
            countries: [
              "US"
            ]
          },
          publisher_platforms: [
            "facebook",
          ],
          facebook_positions: [
            "feed",
          ],
          instagram_positions: [
            "stream",
          ],
          device_platforms: [
            "mobile",
            "desktop",
          ],
        }            
      })

      #Create ad
      ad = ad_account.ads.create({
        status: 'PAUSED',
        name: 'Test ad set',
        adset_id: ad_set.id,
        creative: {
          object_story_spec: {
            page_id: page_id,
            link_data: {
              link: params[:link],
              message: params[:link_title],
              name: "Test",
              attachment_style: "link",
              call_to_action: {
                type: params[:call_to_action]
              }
            }
          },
          title: 'Test title',
          body: 'Test body',
          object_url: params[:link],
          image_file: '/images/vynil.jpg'
        },
        logo: '/images/vynil.jpg'
      })

Thank you!

**Comment by ankitrg** [comment]
I think `object_url: params[:link]` is causing the issue, not sure though.

**Comment by OrrYakobiStudent** [comment]
I believe the issue is somewhere within object_story_spec because I commented out and everything seemed to work fine

**Comment by aribouius** [comment]
@OrrYakobiStudent did you ever find a solution for this?  I'm running into the same problem.
