### ISSUE TITLE
Batch api does not return responses

### ISSUE THREAD

**Issue by osdakira** [facebook/facebook-ruby-business-sdk#66]
### Which SDK version are you using?

```rb
[7] pry(main)> FacebookAds::VERSION
=> "0.3.2.9"
[11] pry(main)> RUBY_VERSION
=> "2.5.0"
```

### What's the issue?

Batch API has the logic to return the response.
However, there is no return value because each_slice has been added.

https://github.com/facebook/facebook-ruby-business-sdk/blob/bd80d59ef8a1f53422d74bb49a917e2a77bebcab/lib/facebook_ads/batch_api/batch.rb#L33-L51

### Steps/Sample code to reproduce the issue

```rb
[4] pry(main)> require "facebookbusiness"
=> true
[5] pry(main)> session = FacebookAds::Session.new(access_token: access_token, app_secret: app_secret)
[6] pry(main)> batch = FacebookAds::Batch.with_batch do
  FacebookAds::AdAccount.get("act_#{ad_account_id}", session).name
[6] pry(main)* end 
[7] pry(main)> batch.execute
=> nil
```

#### Observed Results:

`Enumerable#each_slice` return nil.

https://ruby-doc.org/core-2.5.0/Enumerable.html#method-i-each_slice

#### Expected Results:

I added the `map` method. 
It will be the expected result.

```diff
File: vendor/bundle/ruby/2.5.0/gems/facebookbusiness-0.3.2.9/lib/facebook_ads/batch_api/batch.rb
- 35:       operations.each_slice(50) do |slice|
+ 35:       operations.each_slice(50).map do |slice|
```

```rb
[6] pry(main)> batch.execute
=> [[#<FacebookAds::AdAccount {:id=>"act_****", :account_id=>"****"}>]]
```

**Comment by kurko** [comment]
I have this same issue.

**Comment by raszi** [comment]
This is still an issue!

**Comment by stulzer** [comment]
> This is still an issue, more than three years later! 😞

2025 still an issue.

**Comment by Kcharle** [comment]
Still an issue
