### ISSUE TITLE
https://github.com/facebook/facebook-ruby-business-sdk/blob/8cc041e6f069cec4dd1daff4cdfd47e5a611c5f2/lib/facebook_ads/api_request.rb#L67

### ISSUE THREAD

**Issue by alsfyani** [facebook/facebook-ruby-business-sdk#71]
https://github.com/facebook/facebook-ruby-business-sdk/blob/8cc041e6f069cec4dd1daff4cdfd47e5a611c5f2/lib/facebook_ads/api_request.rb#L67

**Comment by alsfyani** [comment]
! [FB_IMG_1560932705249] (https://user-images.githubusercontent.com/52042760/61156610-78fbea00-a4fc-11e9-9bf0-f2c154a0046b.jpg

**Comment by alsfyani** [comment]
! [FB_IMG_1560932705249] (https://user-images.githubusercontent.com/52042760/61156610-78fbea00-a4fc-11e9-9bf0-f2c154a0046b.jpg)

**Comment by alsfyani** [comment]
FB_IMG_1560932705249 (https://user-images.githubusercontent.com/52042760/61156610-78fbea00-a4fc-11e9-9bf0-f2c154a0046b.jpg)

**Comment by alsfyani** [comment]
> ! [FB_IMG_1560932705249] ( https://user-images.githubusercontent.com/52042760/61156610-78fbea00-a4fc-11e9-9bf0-f2c154a0046b.jpg

**Comment by alsfyani** [comment]
من:‏ Jing Ping
تاريخ الإرسال: الثلاثاء، ٢٣ يوليو ١٢:٠٩ ص
الموضوع:‏ Re: [facebook/facebook-ruby-business-sdk] https://github.com/facebook/facebook-ruby-business-sdk/blob/8cc041e6f069cec4dd1daff4cdfd47e5a611c5f2/lib/facebook_ads/api_request.rb#L67 (#71)
إلى: facebook/facebook-ruby-business-sdk
نسخة: alsfyani, State change


Closed #71<https://github.com/facebook/facebook-ruby-business-sdk/issues/71>.

**Comment by alsfyani** [comment]
https://user-images.githubusercontent.com/52042760/61156610-78fbea00-a4fc-11e9-9bf0-f2c154a0046b.jpg ) - https://m.facebook.com/thjkli.vvthjkfre = ص و__ __ تينيسي = R

**Comment by AlSufyaniT1** [comment]
@AlSufyaniT1
