### ISSUE TITLE
v0.4.0.1 (+3 more versions) not published to Rubygems

### ISSUE THREAD

**Issue by ermanc-salsify** [facebook/facebook-ruby-business-sdk#73]
### Which SDK version are you using?
v0.3.3.3

### What's the issue?
`ids_of_invalid_requests` field missing on `CheckBatchRequestStatus` object

### Steps/Sample code to reproduce the issue
```rb
> resp = catalog.check_batch_request_status(handle: "...handle here...", load_ids_of_invalid_requests: true)
> resp.first.handle
=> "...handle here..."
> resp.first.ids_of_invalid_requests
Traceback (most recent call last):
        1: from (irb):8
NoMethodError (undefined method `ids_of_invalid_requests' for #<FacebookAds::CheckBatchRequestStatus:0x0000...>)>
```

#### Observed Results:
Exception thrown for method not being defined in v0.3.3.3

#### Expected Results:
Being able to use v0.4.0.1 which [has this method/field defined](https://github.com/facebook/facebook-ruby-business-sdk/blob/v0.4.0.1/lib/facebook_ads/ad_objects/check_batch_request_status.rb#L33)

---
Aside from filling out the issue template, my main concern is that `facebookbusiness` gem has not published a new version since v0.3.3.4:
https://rubygems.org/gems/facebookbusiness

whereas Github releases have 4 more versions released since then:
v0.4.0.1
v0.4.0.0
v0.3.3.6
v0.3.3.5
https://github.com/facebook/facebook-ruby-business-sdk/releases

Is it possible that you can publish the missing releases to rubygems?

**Comment by jingping2015** [comment]
Thanks for reporting this issue. I have push v0.4.0.1 and you can check it on rubygems.
