### ISSUE TITLE
Graph API needs to be upgraded to 4.0

### ISSUE THREAD

**Issue by olegpipo** [facebook/facebook-ruby-business-sdk#77]
### Which SDK version are you using?
v0.3.3.1

### What's the issue?
Graph API v3.3 Will No Longer Be Supported

### Steps/Sample code to reproduce the issue
Use any of the methods of the SDK and Facebook will throw this warning

#### Expected Results:
Graph API should be upgraded to 4.0

**Comment by jingping2015** [comment]
Hi, Thanks for report the issue. It has been updated. https://rubygems.org/gems/facebookbusiness

**Comment by jingping2015** [comment]
Please use our latest package to to use Graph API v4.0.
