### ISSUE TITLE
https://www.facebook.com/profile.php?id=‭100005030236147‬

### ISSUE THREAD

**Issue by AlSufyaniT1** [facebook/facebook-ruby-business-sdk#79]
<a class='' href='/developer/clients/manage/'>Manage Clients<i></i></a>`

1. 

- [<link rel = "preload" href = "my-js-file.js" as = "script" type = "text / javascript" />](https://user-images.githubusercontent.com/‭52042760‬/‭61156610-78‬fbea00-a4fc-11e‭9-9‬bf0-f2c‭154‬a‭0046‬b.jpg) 

`

**Comment by alsfyani** [comment]
<a class="_4s19 sec" href="#" role="button" aria-haspopup="true" data-sigil="touchable"></a>

**Comment by alsfyani** [comment]
<a class="_4s19 sec" href="#" role="button" aria-haspopup="true" data-sigil="touchable"></a>

**Comment by alsfyani** [comment]
<a class="_4s19 sec" href="#" role="button" aria-haspopup="true" data-sigil="touchable"></a>

**Comment by AlSufyaniT1** [comment]
<a class="_4s19 sec" href="#" role="button" aria-haspopup="true" data-sigil="touchable"></a>

**Comment by AlSufyaniT1** [comment]
@AlSufyaniT1

**Comment by AlSufyaniT1** [comment]
https://user-images.githubusercontent.com/‭52042760‬/‭61156610-78‬fbea00-a4fc-11e‭9-9‬bf0-f2c‭154‬a‭0046‬b.jpg

**Comment by AlSufyaniT1** [comment]
> [https://user-images.githubusercontent.com/‭52042760‬/‭61156610-78‬fbea00-a4fc-11e‭9-9‬bf0-f2c‭154‬a‭0046‬b.jpg](https://user-images.githubusercontent.com/%E2%80%AD52042760%E2%80%AC/%E2%80%AD61156610-78%E2%80%ACfbea00-a4fc-11e%E2%80%AD9-9%E2%80%ACbf0-f2c%E2%80%AD154%E2%80%ACa%E2%80%AD0046%E2%80%ACb.jpg)

link rel="preload" href="/static/FeedPageContainer.js" as="script" type="text/javascript" />

1. 

- 

> 

> ``
