### ISSUE TITLE
Issue in fetching lead details when using a sample code

### ISSUE THREAD

**Issue by meer-online** [facebook/facebook-ruby-business-sdk#85]
### Which SDK version are you using?
Lastest version
### What's the issue?
The sample code given here to fetch leads data doesn't seem to be working
https://github.com/facebook/facebook-ruby-business-sdk/blob/master/examples/UserLeadGenInfoNode.rb

### Steps/Sample code to reproduce the issue
Just to be clear I did set the access token and other variables needed for this code to return results

#### Observed Results:
its returns the following response with the lead id but none of the details are included.
#<FacebookAds::Lead {:id=>"24595039271296603"}>

  * What happened?  This could be a description, log output, etc.

#### Expected Results:
Lead details should be returned.

  * What did you expect to happen?

Any quick help will be much appreciated.

**Comment by meer-online** [comment]
Also if i use `require 'facebook_ads'` instead of `require 'facebookbusiness'`i get an error 

`undefined method "configure" for FacebookAds:Module (NoMethodError)`

Any thoughts?

**Comment by jingping2015** [comment]
Hi, Thanks for reporting this issue.
Actually you need to specific the fields you want 
```
lead = FacebookAds::Lead.get(id ,'field1, field2,')
```
