### ISSUE TITLE
Include insights in call to account campaigns

### ISSUE THREAD

**Issue by kickbk** [facebook/facebook-ruby-business-sdk#88]
Is there a way to use nested requests to grab insights for each adset like so?

```
params = {
	'time_range': {
		'since': '2019-08-01',
		'until': '2019-08-31',
	}
}
ad_account.campaigns(fields: ['adsets{id, insights{spend, impressions}}'], params: params).to_json
```

Or in other words - Facebook, please get all the adsets in each campaign, and for each adset, please include insights for a specific date range.

How does one request this? It would be wasteful to grab the ID of each adset and then do a call to adset.insights

**Comment by rubyalanis** [comment]
https://www.facebook.com/help/publisher/372100366658322

**Comment by kickbk** [comment]
So, surprisingly, Facebook DOES return insights with my call. Sometimes. No explanation why, but I tried with two accounts and got on one account insights and the other not.
Maybe it has something to do with the insights returned with this call have a shorter lifespan, so you can't get insights for older ads. Not sure. Not going to read through the million of pages.

My solution, for whoever is interested.
I made a call to adaccount insights directly, and specified the level as 'ad' so ir will return insights for all the account ads. I also requested the 'ad_id'. Later I was able to match the results returned with this call to the previous call I mentioned by comparing the ad ID, and merge the results.

```
ad_account.insights(
	fields: ['ad_id', 'spend', 'impressions', 'clicks', 'ctr', 'cpc'], 
	level: 'ad',
	time_range: {
		since: date_since,
		until: date_until
	}
).to_json
```
